spell.out: spellcheck.o hash.o
	g++ -o spell.out spellcheck.o hash.o -std=c++11

spellcheck.o: spellcheck.cpp hash.h
	g++ -c spellcheck.cpp -std=c++11

hash.o: hash.cpp hash.h
	g++ -c hash.cpp -std=c++11

debug:
	g++ -g -o spellDebug.exe spellcheck.cpp hash.cpp

clean:
	rm -f *.exe *.o *.stackdump *~

backup:
	test -d backups || mkdir backups
	cp *.cpp backups
	cp *.h backups
